default_platform(:ios)

platform :android do
  desc "Submit to Firebase App Distribution"
  lane :push_firebase_release do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      apk_path: 'android/app/build/outputs/apk/release/app-release.apk',
      groups: 'unlitter-usa-testers',
      service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"]
    )
  end

  desc "Bump version code Android"
  lane :bump_version_android do
    increment_version_code(
      gradle_file_path: "android/app/build.gradle"
    )
  end
  desc "Bump version number Android"
  lane :version_number do |options|
    increment_version_name(
      version_name: options[:CODE],
      gradle_file_path: "android/app/build.gradle"
    )
  end
end

platform :ios do
  desc 'Increment version number to AppStore'
  lane :version_number do |options|
    increment_version_number(
      version_number: options[:CODE],
      xcodeproj: ENV['XCODEPROJ_PATH']
    )
  end
  desc 'Increments patch build version'
  lane :build_version do
    increment_build_number(
      xcodeproj: ENV['XCODEPROJ_PATH']
    )
  end

  desc "Push a new build to Testflight"
  lane :push_testflight_release do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      is_key_content_base64: true,
    )
    ipa_path = ENV['APP_IPA_PATH']
    upload_to_testflight(
      api_key: api_key,
      submit_beta_review: false,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
    )
  end


  desc "Build new .ipa file"
  lane :beta do
    setup_ci if ENV['CI']
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      is_key_content_base64: true,
    )

    match(
      type: 'appstore',
      app_identifier: ENV['APP_IDENTIFIER'],
      api_key: api_key,
      readonly: false,
      storage_mode: "git",
      git_url: ENV['GIT_URL'],
      username: ENV['GIT_USERNAME'],
      git_private_key: ENV['GIT_PRIVATE_KEY']
    )

    build_app(
      configuration: "Release",
      scheme: ENV['XCODE_SCHEMA'],
      archive_path: ENV['XARCHIVE_PATH'],
      workspace: ENV['XWORKSPACE_PATH'],
      export_method: 'app-store',
      export_team_id: ENV['IOS_TEAM_ID'],
    )
  end
end
